name: Deploy Site to Pages

on:
  push:
    branches: ["main"]

    paths:
      - docs/**
      - .github/**
      - keygen/**

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Build & Deploy Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: ">=22"

      - name: Load keys
        run: |
          npm i -g pnpm
          pnpm install
          node load.js
        env:
          MONGODB: ${{ secrets.MONGODB_CREDENTIALS }}
          KEY_FILE_INTEGRITY: ${{ secrets.KEY_FILE_INTEGRITY }}
        working-directory: keygen

      - name: Build Pages
        run: |
          npm i -g pnpm

          pnpm install
          pnpm docs:build
        working-directory: docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./docs/.vitepress/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
